config/routes.rb
Rails.application.routes.draw do

  resources :raffle_emails
  resources :events
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#landing_page_drawing'

  get 'coolest_demo_ever' => 'pages#landing', as: :demo

  post 'stripe_checkout' => 'subscriptions#stripe_checkout', as: :stripe_checkout

  get 'subscriptions/plans'

  get 'subscriptions/index'

  get 'privacy-policy' => 'pages#privacy', as: :privacy_policy

  resources :videos

  resources :charges

  get "this_is_so_cool" => 'raffle_emails#raffle_share', as: :raffle_share

  post "welcome_email", to: 'raffle_emails#welcome_email', as: :welcome_email

  get 'color_fun' => 'pages#color_fun', as: :color_fun_path
  # get 'charges/create' => 'charges#create', as: :create_new_charge

  get 'create_new_video' => 'videos#create_new_video', as: :create_new_video

  get 'check_video_progress' => 'videos#check_video_progress'

  # get "/auth/:action/callback", :controller => "omniauth_callbacks", :constraints => { :action => /instagram|youtube/ }
  get 'upload_confirmation' => 'videos#upload_confirmation', as: :upload_confirmation

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  title               :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  music_url           :string
#  non_music_url       :string
#  done_editing        :boolean          default(FALSE), not null
#  video_type          :integer
#  uid                 :string
#  description         :text
#  event_id            :integer
#  no_instagram_videos :boolean          default(FALSE)
#

class Video < ApplicationRecord
  belongs_to :user

  enum video_type: [:free, :paid]

  before_create :create_description


  def create_description
    self.description = "Here's this month's instagram compilation!\n\n\n\nIt was automatically made with the video editing A.I. at www.velvi.io."
  end

  def upload_to_youtube(vid_type='music')
    titty = "Instagram Compilation #{self.created_at.strftime("%B, %Y")}"
    temp_params = { title: titty, description: self.description, category: 'Sports',
                  keywords: ['parkour', 'freerunning', 'instagram', 'extreme sports'] }
                  #TODO Save tags as part of video and use those here

    refresh_token = self.user.youtube_refresh_token
    access_tokn = self.user.youtube_token
    Yt.configuration.client_id = ENV['VELVI_YOUTUBE_CLIENT_ID']
    Yt.configuration.client_secret = ENV["VELVI_VIDEO_INSTA_SECRET"]
    account = Yt::Account.new(access_token: access_tokn)
    vid_type == 'music' ? vid = self.music_url : vid = self.non_music_url
    puts "\n\n=====\n\n\n====ACCOUNT=============\n\n#{account.access_token}\n\n============\n\n\n==============\n\n\n\n"
    account.upload_video vid, temp_params
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  ## TODO Make a modal for loading screen
  ## add bootstrap
  def new
    session[:vid_id] = nil
  end

  def show
    @video = Video.find(params[:id])
    session[:vid_id] = params[:id]
  end

  def index
    puts session[:vid_id]
    if user_signed_in?
      if current_user.videos.present?
        @videos = current_user.videos.all
      end
    end
  end

  def upload_confirmation
    video = Video.find(params[:vid_id])
    video.upload_to_youtube
    redirect_to video_path(video)
    flash[:success] = "Successfully Uploaded To Youtube!"
  end

  def check_video_progress
    vid = Video.find(params[:vid_id])
    respond_to do |format|
      format.json { render json: { done_editing: vid.done_editing }}
    end
  end

  def create_new_video
    current_user.update(email: params[:user_email])
    vid = current_user.videos.create(title: "#{Time.now.strftime("%m/%d/%Y")}-video", video_type: params[:version])
    current_user.call_movie_creation_worker
    respond_to do |format|
       format.json { render json: { video_id: vid.id } }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<div class="container">

  <% if user_signed_in %>
    <h1><%= link_to "Create A Video", new_video_path %></h1>
  <% else %>
    <%= link_to "Get Started", user_instagram_omniauth_authorize_path, class:'btn btn-danger main-login-button' %>
  <% end  %>

  <div class="container">
    <h2><strong style='color:red'>IMPORTANT! Because we use ffmpeg, the audio isn't compatible with quicktime or safari. You might want to try out <a href="https://www.videolan.org/vlc/">VLC</a></strong></h2>
  </div>
  <div class="container">
    <% if @videos != nil %>
    <% @videos.each do |video| %>
      <div class="card">
        <h1>Video <%= video.id %></h1>
        <video width="1100" controls>
          <source src="<%= video.music_url %>" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>

       <h4> Music</h4>
        <a href="<%= video.music_url %>" class='btn btn-success' download>Download!</a>
        <h4>Without Music</h4>
        <a href="<%= video.non_music_url %>" class='btn btn-success' download>Download!</a>
        <hr>
      </div>
    <% end %>
    <% else %>
      <h1>You don't have any videos yet!</h1>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container">
  <br>
  <h1>Try The Demo<h1>
    <h5>Here's what will happen</h5>
  <br><br>
  <div class="row">
    <div class="col-lg-5">
      <div class="card">
        <div class="container">
        <h2>The A.I. Will </h2>
        <br>
        <ol>
          <h5><li>Take the videos from your instagram </li></h5>
          <h5><li>Run A.I. magic</li></h5>
          <h5><li>Add them together</li></h5>
          <h5><li>Add some tunes</li></h5>
        </ul>
        <br>
      </div>
        <button class='btn btn-danger' id='createFreeVideoBtn'>Show Me The Magic</button>
      </div>
    </div>
    <!-- <div class="col-lg-2" style='text-align:center'>
        <h1>Or</h1>
    </div>
    <div class="col-lg-4 ">
      <div class="card" style='margin-left:0px;'>
        <div class="container">
        <h3>$7 - Premium Video </h3>
        <ul>
          <li>No Logo!</li>
        </ul>
      </div>
        <button class='btn btn-primary' id='createVideoBtn'>One Click Video - $7</button>
      </div>
    </div>
  </div> -->

  <div class="">
    <br><br>
    <div class=" row">
      <div class="col-sm-1">
        <div class="newVidCheckBox">
          <input type="checkbox" value="" id="newVidCheckBox" name="check" checked />
          <label for="newVidCheckBox"></label>
        </div>
      </div>
      <div class="col-sm-11">
        <h5>Auto-Post To YouTube Because You're Awesome</h5>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class='container loader'></div>
        <div class="c">
          <h1>Building Your Video</h1>
          <h4>This may take up to 5 minutes. :)</h4>
        </div>
      </div>
    </div>
  </div>
</div>


<% ['free', 'paid'].each do |modal_type| %>
  <div class="modal fade" id="<%= modal_type %>youTubeModal" aria-hidden="true">
    <div class="modal-dialog" role="">
      <div class="modal-content">
        <div class="modal-header">
        </div>
        <div class="modal-body">
          <div class='container'></div>
          <div class="" style='text-align:center'>
            <h1>Auto-Post To YouTube</h1>
            <div class="">
              <br>
              <div class="row">
                <div class="col-md-6">
                  Sign In To YouTube
                  <div class="card">
                    <h5>I Want To Be Awesome</h5>
                    <%= link_to "Be Awesome", user_google_oauth2_omniauth_authorize_path(), class:'btn btn-danger' %>
                  </div>
                </div>
                <%= hidden_field_tag 'userEmail', current_user.email%>

                <div class="col-md-6">
                  <br>
                  <div class="card">
                    <h5>I Want To Be Lame</h5>
                    <button type="button" id='lamoButton' class='btn btn-primary' name="button">Be Lame</button>
                    <form id='<%= modal_type %>lamoForm' action="/action_page.php" hidden>
                      Add Your Email: <input type="text" name="usremail" id='<%= modal_type %>usrEmailInput'><br>
                      <input type="submit" value="Create My Video" class='btn btn-primary' id='<%= modal_type %>UsrEmailSubmit'>
                    </form>
                  </div>
                </div>
              </div>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


<script type="text/javascript">

    $(document).ready(function() {

      $("#createVideoBtn").click(function() {
        checkStuffThenCreateVideo('paid')
      });

      $("#createFreeVideoBtn").click(function() {
        checkStuffThenCreateVideo('free')
      });

      $("#lamoButton").click(function(){
        document.getElementById('freelamoForm').removeAttribute("hidden");
      });


      $("#freelamoForm").on("submit", function(e){
        e.preventDefault();
        $('#freeyouTubeModal').modal("hide");
        document.getElementById("newVidCheckBox").checked = false
        checkStuffThenCreateVideo('free')
      })
    });

    function checkStuffThenCreateVideo(video_type){
      var youtube_uid = <%= current_user.youtube_uid.present? %>
      var checkBoxValue = document.getElementById("newVidCheckBox").checked
      console.log(checkBoxValue)
      if(checkBoxValue){
        if (youtube_uid){
          beginVideoCreation(video_type)
        }else{
          signInToYoutube(video_type)
        }
      }else{
        beginVideoCreation(video_type)
      }
    }

    function beginVideoCreation(video_type){
      console.log("Im working")
      var emailField = "#" + video_type + "usrEmailInput"
      console.log(emailField)
      if($(emailField).val() != 'nil'){
        var u_email = $(emailField).val()
      }else if($("#userEmail") != 'nil'){
        var u_email = $("#userEmail").val()
      };
      $('#myModal').modal("show");
      $.get(window.location.origin+'/create_new_video',  {version: video_type, user_email: u_email}, function(data){
        var vid_id = data['video_id']
        setInterval(function(){
          $.get(window.location.origin+'/check_video_progress', {vid_id: vid_id}, function(data){
            console.log(data['done_editing'])
            if(data['done_editing'] === true){
              window.location.href = '/videos/'+vid_id
            }
          });
        }, 3000);
      })
    }

    function signInToYoutube(video_type){
      if(video_type == 'free'){
        $('#freeyouTubeModal').modal("show");
      }else{
        $('#paidyouTubeModal').modal("show");
      }
    }

</script>

app/views/videos/show.html.erb
<% content_for :meta do %>
  <meta property="og:url" content="<%= "www.velvi.io/videos#{@video.id}" %>" />
  <meta property="og:type" content="video.other" />
  <meta property="og:title" content="<%= @video.title.split('-').first %> Instagram Compilation" />
  <meta property="og:video" content="<%= @video.music_url %>">
  <meta property="og:video:secure_url" content="<%= @video.music_url %>" />
  <meta property="og:video:type" content="application/x-shockwave-flash" />
  <meta property="og:video:width" content="400" />
  <meta property="og:video:height" content="300" />
<% end %>


<div class="container">
  <% if @video.no_instagram_videos != true %>

      <br>
      <h2><strong style='color:red'>IMPORTANT! Because we use ffmpeg, the audio isn't compatible with quicktime or safari. You might want to try out <a href="https://www.videolan.org/vlc/">VLC</a></strong></h2>
      <div class='social-share'>
        <h4 class='title'><strong>Share This Video!</strong></h4>
        <!-- <a class="social-link facebook" href="" id="fb-share" rel="nofollow" target="_blank" title="Share on Facebook"><i class="fa fa-facebook"></i>Facebook</a> -->
        <a class="social-link twitter" href="" id="tweet" rel="nofollow" target="_blank" title="Tweet this Page"><i class="fa fa-twitter"></i> Tweet</a>
        <a class="social-link email" href="" id="email-share" title="Email to a Friend"><i class="fa fa-envelope"></i>Email</a>
        <div class="fb-like" data-share="true" data-width="450" data-show-faces="true">
      </div><br>
      <div class="social-share">
        <% if current_user == @video.user %>
          <h4 class='title'>Upload To YouTube With One Click!</h4>
          <% if current_user.youtube_uid == nil %>
            <%= link_to "Sign In With YouTube First", user_google_oauth2_omniauth_authorize_path(), class:'btn btn-danger' %>
          <% else %>
            <%= link_to "One Click Upload!", upload_confirmation_path(vid_id: @video.id), class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
      <h3><%= @video.title.split('-').first %> Instagram Compilation</h3>
      <div class="card">
        <h1>Video With Song</h1>
        <video width="1100" controls>
          <source src="<%= @video.music_url %>" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
        <br>

        <div class='social-share'>
          <h4 class='title'><strong>Share This Link!</strong></h4>
      	  <!-- <a class="social-link facebook" href="" id="fb-share" rel="nofollow" target="_blank" title="Share on Facebook"><i class="fa fa-facebook"></i>Facebook</a> -->
      		<a class="social-link twitter" href="" id="tweet" rel="nofollow" target="_blank" title="Tweet this Page"><i class="fa fa-twitter"></i> Tweet</a>
      		<a class="social-link email" href="" id="email-share" title="Email to a Friend"><i class="fa fa-envelope"></i>Email</a>
          <div class="fb-like" data-share="true" data-width="450" data-show-faces="true">
        </div><br>
        <a href="<%= @video.music_url %>" class='btn btn-success' download>Download!</a>
        <h1>Video With Natural Audio</h1>
        <video width="1100" controls>
          <source src="<%= @video.non_music_url %>" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
        <br>

        <div class='social-share'>
          <h4 class='title'><strong>Share This Link!</strong></h4>
          <a class="social-link facebook" href="" id="fb-share" rel="nofollow" target="_blank" title="Share on Facebook"><i class="fa fa-facebook"></i>Facebook</a>
      		<a class="social-link twitter" href="" id="tweet" rel="nofollow" target="_blank" title="Tweet this Page"><i class="fa fa-twitter"></i> Tweet</a>
      		<a class="social-link email" href="" id="email-share" title="Email to a Friend"><i class="fa fa-envelope"></i>Email</a>
        </div><br>
        <a href="<%= @video.non_music_url %>" class='btn btn-success' download>Download!</a>
        <hr>
      </div>
  <% else %>
      <div class="jubotron">
        <h1>You Don't Have Any Videos On Your Instagram!</h1>

        <h3>We use the videos to make on compilation for you.</h3>
      </div>
  <% end %>
</div>

<script type="text/javascript">
  jQuery(document).ready(function($){
  function getFBShares(page){
    var shares;
    $.getJSON("http://graph.facebook.com/?ids=" + page, function(data){
      if (data[page].shares > 1){
        shares = data[page].shares;
        $("#fb-share").append(" (" + shares + ")");
      }
    });
  }
  function getTweets(page){
    var tweets;
    $.getJSON("http://urls.api.twitter.com/1/urls/count.json?url=" + page + "&callback=?", function(data){
      if (data.count > 1) {
        tweets = data.count;
        $("#tweet").append(" (" + tweets + ")");
      }
    });
  }
  function getLinkedIn(page){
    var linkedinCount;
    $.getJSON("http://www.linkedin.com/countserv/count/share?url=" + page + "&callback=?", function(data){
      if (data.count > 1) {
        linkedinCount = data.count;
        $("#linkedin").append(" (" + linkedinCount + ")");
      }
    });
  }

  var Url = "https://www.velvi.io/videos/<%= @video.id %>";
  var UrlEncoded = encodeURIComponent(Url);
  getFBShares(Url);
  getTweets(Url);
  getLinkedIn(Url);
  document.getElementById("fb-share").href="http://www.facebook.com/share.php?u=" + UrlEncoded;
  document.getElementById("tweet").href="http://twitter.com/home?status=Check out my instagram compilation! I made it with Velvi " + UrlEncoded;
  document.getElementById("gplus-share").href="https://plus.google.com/share?url=" + UrlEncoded;
  document.getElementById("email-share").href="mailto:?body=Hey, out my instagram compilation! I made it with Velvi! \n " + Url;
  });

</script>

app/views/videos/upload_confirmation.html.erb
<div class="container" style='text-align:center'>
  <h1>We're Sending Your Video To Your YouTube Account</h1>
  <h3>You'll be redirected when it's done. :)</h3>
</div>