config/routes.rb
Rails.application.routes.draw do

  resources :raffle_emails
  resources :events
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#landing_page_drawing'

  get 'coolest_demo_ever' => 'pages#landing', as: :demo

  post 'stripe_checkout' => 'subscriptions#stripe_checkout', as: :stripe_checkout

  get 'subscriptions/plans'

  get 'subscriptions/index'

  get 'privacy-policy' => 'pages#privacy', as: :privacy_policy

  resources :videos

  resources :charges

  get "this_is_so_cool" => 'raffle_emails#raffle_share', as: :raffle_share

  post "welcome_email", to: 'raffle_emails#welcome_email', as: :welcome_email

  get 'color_fun' => 'pages#color_fun', as: :color_fun_path
  # get 'charges/create' => 'charges#create', as: :create_new_charge

  get 'create_new_video' => 'videos#create_new_video', as: :create_new_video

  get 'check_video_progress' => 'videos#check_video_progress'

  # get "/auth/:action/callback", :controller => "omniauth_callbacks", :constraints => { :action => /instagram|youtube/ }
  get 'upload_confirmation' => 'videos#upload_confirmation', as: :upload_confirmation

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/color_fun.html.erb
<% @c.each_slice(12) do |colors| %>
  <div class="row">
    <% colors.each do |color| %>
      <div class="col-sm-1" style='background-color: <%= color %>; min-height:120px;border-radius:100px;'>

      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/landing.html.erb
<% content_for :meta do %>
<meta property="og:url"                content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
<!-- <meta property="og:type"               content="article" /> -->
<meta property="og:title"              content="Velvi" />
<meta property="og:description"        content="Video Compilation A.I. A HollyWood Studio In Your Pocket" />
<meta property="og:image"              content="https://images.pexels.com/photos/947785/pexels-photo-947785.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" />
<% end %>
<div class=''>
  <!-- <div class="jumbotron">
    <h1 style='font-size:80px'>Velvi Videos</h1>

    <h5>Automatic video compilation.</h5>

  </div> -->

  <header class="header-image all-content">
    <div class="over-lay">

        <div class="headline">
            <div class="container">
                <h2 class='main-title'>Art Shoudl Be Fun</h2>
                <h5>Try The Demo With Instagram</h5>
                <% unless user_signed_in? %>
                  <%= link_to "Get Started", user_instagram_omniauth_authorize_path, class:'btn btn-danger main-login-button' %>
                <% else %>
                    <h5>
                      <%= link_to 'Create Your Video!', new_video_path, class: 'btn btn-danger main-login-button' %>
                    </h5>
                <% end %>
            </div>
        </div>
      </div>
    </header>
    <!-- <br>
    <br>
    <br>
    <br>
    <br>
    <div class="row" style='margin-left:400px;'>
      <%#= image_tag "http://www.freeiconspng.com/uploads/--in-blow-to-crafty-brand-odes-instagram-adopts-minimalist-new-logo-16.jpg", size:'50x50'  %>
      <div class="row" style='margin-top:4.5px;margin-left:0px;'>
        <h4 style='margin-top:14px'>www.</h4>
        <h1 class='' style='font-weight:bold;'>Velvi </h1>
        <h4 style='margin-top:14px'>.io</h4>

      </div>

    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br> -->

    <!-- <h3><%#= link_to "My Videos", videos_path %></h3> -->

    <!-- Page Content -->
    <div class="container">

          </div>

        <br class="featurette-divider">
        <br class="featurette-divider">
        <br class="featurette-divider">
        <br class="featurette-divider">
        <br class="featurette-divider">

        <!-- First Featurette -->
        <div class="featurette row" id="about">
          <div class="col-sm-6 inner-text">
            <br>
            <h2 class="featurette-heading">Sync Your Instagram!</h2>

          </div>
          <div class="col-sm-6 text-center">
            <!-- <img class="featurette-image img-circle img-responsive pull-right" src="http://placehold.it/100x100"> -->
            <%= image_tag "http://www.freeiconspng.com/uploads/--in-blow-to-crafty-brand-odes-instagram-adopts-minimalist-new-logo-16.jpg", size:'150x150' %>
          </div>
            <!-- <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p> -->
        </div>

        <hr class="featurette-divider">

        <!-- Second Featurette -->
        <div class="featurette row text-center" id="services">
          <div class="col-sm-6 ">
            <%= image_tag "https://image.freepik.com/free-icon/video-camera_318-50337.jpg", size:'150x150' %>


          </div>
          <div class="col-sm-6 text-right inner-text">
            <br>
            <h2 class="featurette-heading">With One Click, We'll Create Your Video</h2>

          </div>
            <!-- <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p> -->
        </div>

        <hr class="featurette-divider">

        <!-- Third Featurette -->
        <div class="featurette row" id="contact">
          <div class="col-sm-6 inner-text">
            <br>
            <h2 class="featurette-heading">Enjoy Your Movie!</h2>

          </div>
          <div class="col-sm-6 text-center">
            <!-- <img class="featurette-image img-circle img-responsive pull-right" src="http://placehold.it/100x100"> -->
            <%= image_tag "http://icons.iconarchive.com/icons/iconsmind/outline/512/Happy-icon.png", size:'150x150' %>
          </div>
                <!-- <span class="text-muted">Will Seal the Deal.</span> -->
            <!-- <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p> -->
        </div>

        <hr class="featurette-divider">
        <div class="text-center">
          <% unless user_signed_in? %>
            <%= link_to "Get Started", user_instagram_omniauth_authorize_path, class:'btn btn-danger' %>
          <% else %>
              <h5>
                <%= link_to 'Create Your Video!', new_video_path, class: 'btn btn-danger' %>
              </h5>
          <% end %>
        </div>


</div>

  <!-- , {'data-target' => "#myModal1", 'data-toggle' => "modal"} -->

app/views/pages/landing_page_drawing.html.erb
    <div class="center-logo">
      <%#= image_tag "Brain\ Black.png", size: '400x450' %>
      <%= image_tag "Brain.png", size: '450x450' %>
      <h1 class="mb-5 asbf">Art Should Be Fun.</h1>
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <%= link_to "Learn More", "#{root_path}#explainer-video", class: 'btn btn-outline' %>
          <%= link_to "Try the demo", demo_path, class: 'btn btn-outline' %>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
    <header class="masthead">
      <div class="over-lay h-100">

      <div class="container h-100">
        <div class="row h-100">
          <div class="col-lg-7 my-auto">
            <div class=" mx-auto">
              <!-- <h2>That's why we built an A.I. to help you edit videos</h2> -->
              <h1>A.I. For Video Editing</h1>
              <div class="row">
                <%= link_to "Learn More", "#{root_path}#explainer-video", class: 'btn btn-outline' %>
                <%= link_to "Try the demo", demo_path, class: 'btn btn-outline' %>
              </div>
              <!-- <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">GoPro Hero 5 Giveaway</a> -->
            </div>
          </div>
          <div class="col-lg-5 my-auto">
            <div class="device-container">
              <div class="device-mockup iphone6_plus portrait white">
                <div class="device">
                  <div class="screen">
                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                    <!-- <%= image_tag('app/assets/images/adult-beard-blur.jpg') %> -->
                    <!-- <img src="adult-beard-blur.jpg" class="img-fluid" alt=""> -->
                  </div>
                  <div class="button">
                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </header>
<div class="video" id='explainer-video'>
  <h1>Watch The Explainer Video!</h1>
  <div class='embed-div'>
        <%= content_tag(:iframe, nil, src: "https://www.youtube.com/embed/CmG6JznfmZw", class:['embed-container']) %>
  </div>
</div>

    <section class="features card" id="features">
      <div class="container " id='signup-form'>
        <div class="section-heading text-center">
          <h1>Learn When We Launch Our Kickstarter!</h1>
        </div>
          <div class="container main-email-form" >
              <%= form_for @raffle_email do |f| %>
              <div class="row">
                <div class="col-lg-3">

                </div>
                <div class="col-lg-2">
                  <!-- <%#= f.label :name %><br> -->
                  <h4>Name</h4>
                  <%= f.text_field :name %>
                </div>
                <div class="col-lg-3">
                  <!-- <%#= f.label :email %><br> -->
                  <h4>Email</h4>
                  <%= f.text_field :email %>
                </div>
                <div class="col-lg-1">
                  <br>
                  <%= f.submit "Keep In Touch", class: 'btn btn-primary' %>
                </div>
              </div>

              <% if flash[:alert] %>
                <div class="notice text-center">
                  <h5> <%= flash[:alert] %></h5>
                </div>
              <% end %>

              <% end %>
          </div>
          <hr>
        <!-- <div class="row">
          <div class="col-lg-4 my-auto">
            <div class="device-container">
              <div class="device-mockup iphone6_plus portrait white">
                <div class="device">
                  <div class="screen">
                    <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                  </div>
                  <div class="button">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-8 my-auto">
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-screen-smartphone text-primary"></i>
                    <h3>Device Mockups</h3>
                    <p class="text-muted">Ready to use HTML/CSS device mockups, no Photoshop required!</p>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-camera text-primary"></i>
                    <h3>Flexible Use</h3>
                    <p class="text-muted">Put an image, video, animation, or anything else in the screen!</p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-present text-primary"></i>
                    <h3>Free to Use</h3>
                    <p class="text-muted">As always, this theme is free to download and use for any purpose!</p>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-lock-open text-primary"></i>
                    <h3>Open Source</h3>
                    <p class="text-muted">Since this theme is MIT licensed, you can use it commercially!</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> -->
      </div>
    </section>

    <section class="cta">
      <div class="over-lay">
        <div class="container">

          <div class="cta-content">
            <div class="container">
              <h2><br><strong>Be The First To Know.</strong></h2>
              <%= link_to "Keep Me Updated!", "#{root_path}#signup-form", class:'btn btn-outline' %>
              <!-- <a href="#contact" class="btn btn-outline btn-xl js-scroll-trigger">Let's Get Started!</a> -->
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- <section class="contact bg-primary" id="contact">
      <div class="container">

        <ul class="list-inline list-social">
          <li class="list-inline-item social-twitter">
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item social-facebook">
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item social-google-plus">
            <a href="#">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        </ul>
      </div>
    </section> -->



    <!-- Bootstrap core JavaScript -->



    <!-- <source src="https://youtu.be/CmG6JznfmZw" type="video/youtube"> -->


    <!-- <section class="download bg-primary text-center" id="download">
    <div class="container">
    <div class="row">
    <div class="col-md-8 mx-auto">
    <h2 class="section-heading">Why Is Everyone So Excited?</h2>
    <h4>Because Our A.I. helps you edit your videos 100x faster, while letting you add your own style and creative expression</h4>
    <div class="badges">
    <!-- <a class="badge-link" href="#"></a>
    <a class="badge-link" href="#"></a>
  </div>
</div>
</div>
</div>
</section> -->