config/routes.rb
Rails.application.routes.draw do

  resources :raffle_emails
  resources :events
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#landing_page_drawing'

  get 'coolest_demo_ever' => 'pages#landing', as: :demo

  post 'stripe_checkout' => 'subscriptions#stripe_checkout', as: :stripe_checkout

  get 'subscriptions/plans'

  get 'subscriptions/index'

  get 'privacy-policy' => 'pages#privacy', as: :privacy_policy

  resources :videos

  resources :charges

  get "this_is_so_cool" => 'raffle_emails#raffle_share', as: :raffle_share

  post "welcome_email", to: 'raffle_emails#welcome_email', as: :welcome_email

  get 'color_fun' => 'pages#color_fun', as: :color_fun_path
  # get 'charges/create' => 'charges#create', as: :create_new_charge

  get 'create_new_video' => 'videos#create_new_video', as: :create_new_video

  get 'check_video_progress' => 'videos#check_video_progress'

  # get "/auth/:action/callback", :controller => "omniauth_callbacks", :constraints => { :action => /instagram|youtube/ }
  get 'upload_confirmation' => 'videos#upload_confirmation', as: :upload_confirmation

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  require "stripe"

  def create
    subscription = Stripe::Plan.create(
      :amount => (params[:amount].to_i)*100,
      :interval => params[:interval],
      :name => params[:name],
      :currency => 'usd',
      :trial_plan => null,
      :id => SecureRandom.uuid # This ensures that the plan is unique in stripe
    )
    #Save the response to your DB
    flash[:notice] = "Plan successfully created"
    redirect_to '/subscription'
  end

  def stripe_checkout
    @amount = 10
    #This will create a charge with stripe for $10
    #Save this charge in your DB for future reference
    charge = Stripe::Charge.create(
                    :amount => @amount * 100,
                    :currency => "usd",
                    :source => params[:stripeToken],
                    :description => "Test Charge"
    )
    flash[:notice] = "Successfully created a charge"
    redirect_to '/subscription'
  end

  def plans
  end

  def index
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.haml
%h1 Create a new subscription
= form_tag('/subscription',{method: :post}) do
  .form-group
    %label Plan name
    %input{:type => 'text', :name => 'name'}
  .form-group
    %label Plan interval
    = select_tag 'interval', options_for_select(['month', 'year']), multiple: false, :include_blank => true,  class: "form-control"
  .form-group
    %label Plan Value
    %input{:type => 'text', :name => 'amount'}

  %button{:type => "submit"} Submit to Stripe

app/views/subscriptions/plans.html.erb
<h1>Subscriptions#plans</h1>
<p>Find me in app/views/subscriptions/plans.html.erb</p>

app/views/subscriptions/stripe_checkout.html.erb
<%= form_tag stripe_checkout_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>$
      </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>",
          data-description="Credits",
          data-amount= 7.0,
          data-email = "customer@example.com",
          data-currency = "USD"
          data-locale= "auto"></script>
<% end %>